export const speaker = [
  {
    title: "Women in Tech_",
    persons: [],
  },
  {
    title: "AMA_",
    persons: [],
  },
  {
    title: "Workshops_",
    persons: [],
  },
  {
    title: "Tech Talks_",
    persons: [
      {
        topic: "Android + Kotlin: Jetpack Compose experience",
        firstName: "Zolboobayar",
        lastName: "Gantumur",
        role: "Tech Lead",
        work: "Meta Global Inc LLC",
        picture: "Zolboobayar_Gantumur",
      },
      {
        topic: "Native to Hybrid, Hybrid development",
        firstName: "Usukhbayar",
        lastName: "Ganbaatar",
        role: "Sr Mobile Developer",
        work: "Mezorn",
        picture: "Zolboobayar_Gantumur",
      },
      {
        topic: "GraphQL / Mobile",
        firstName: "Gansoronzon",
        lastName: "Norovgachil",
        role: "Sr Mobile Engineer",
        work: "Meta / Facebook",
        picture: "Zolboobayar_Gantumur",
      },
      {
        topic: "Women in Tech & Web Development",
        firstName: "Anu",
        lastName: "Otgonjargal",
        role: "Front-end Developer",
        work: "Steppelink LLC",
        picture: "Zolboobayar_Gantumur",
      },
      {
        topic:
          "Efficiency and Optimization of Design System and how it effects consistency of products",
        firstName: "Ariunaa",
        lastName: "Ganbat",
        role: "UX / UI designer",
        work: "And Systems Tech",
        picture: "Zolboobayar_Gantumur",
      },
      {
        topic: "Keeping up with education with AI",
        firstName: "Tuvshintur",
        lastName: "Tserendorj",
        role: "Founder",
        work: "KMP",
        picture: "Tuvshintur_Tserendorj",
      },
      {
        topic: "Recommendation System",
        firstName: "Tungalag",
        lastName: "Ziinaa",
        role: "Data Scientist",
        work: "Freelancer",
        picture: "Tungalag_Ziinaa",
      },
      {
        topic: "What is Music and AI? How AI/ML composes music?",
        firstName: "Khongorzul",
        lastName: "Munkhbat",
        role: "ML Engineer",
        work: "MMusic",
        picture: "Khongorzul_Munkhbat",
      },
      {
        topic:
          "CI/CD concepts apply to traditional software engineering, but they apply just as well to machine learning systems and are a critical part of MLOps strategy. After successfully developing a model, a data scientist should push the code, metadata, and documentation to a central repository and trigger a CI/CD pipeline. So what exactly should the CI/CD pipeline be?",
        firstName: "Tumur-Ochir",
        lastName: "Nasanjargal",
        role: "Senior ML Engineer",
        work: "And Systems Tech LLC",
        picture: "Khongorzul_Munkhbat",
      },
      {
        topic: "Building Decentralized Applications (dapp)",
        firstName: "Munkh-Od",
        lastName: "Ganzorigt",
        role: "CTO",
        work: "DiverseSolutions",
        picture: "Munkh-Od_Ganzorigt",
      },
      {
        topic: "Smart contract on UTXO model",
        firstName: "Tuvshintsenguun",
        lastName: "Erdenejargal",
        role: "Software Test Engineer",
        work: "Input Output Global",
        picture: "Munkh-Od_Ganzorigt",
      },
      {
        topic: "Effectiveness of Security Controls",
        firstName: "Ganbayar",
        lastName: "Uuganbayar",
        role: "Cyber security researcher",
        work: "University of Oxford",
        picture: "Munkh-Od_Ganzorigt",
      },
      {
        topic:
          "New Laws / Regulations in Mongolia about PII, Cybersecurity, Opendata",
        firstName: "Tengis",
        lastName: "Sukhee",
        role: "Information security advisor",
        work: "Indepenent",
        picture: "Tengis_Sukhee",
      },
      {
        topic: "Migrating microservices (Java, NodeJS) into Kubernetes",
        firstName: "Bilguun",
        lastName: "Bayarmagnai",
        role: "CTO",
        work: "Nomadays LLC",
        picture: "Tengis_Sukhee",
      },
      {
        topic:
          "Web app & Browser extension integration test (Selenium WebDriver + Puppeteer)",
        firstName: "Bilguun",
        lastName: "Bayarsaikhan",
        role: "Senior Software Engineer",
        work: "Unimedia Solutions",
        picture: "Tengis_Sukhee",
      },
      {
        topic: "CI/CD",
        firstName: "Dulmandakh",
        lastName: "Sukhbaatar",
        role: "Founder / CEO",
        work: "Khuur Music Group LLC",
        picture: "Tengis_Sukhee",
      },
      {
        topic:
          "Structured and centralized logging service, Monitoring your systems and services, Alerting on thresholds, integrations for logging, monitoring, and alerting",
        firstName: "Lkhavuujal",
        lastName: "Nipra",
        role: "Director of DevOps Division",
        work: "Grapecity Mongolia LLC",
        picture: "Tengis_Sukhee",
      },
      {
        topic: "Serverless IoT Architecture",
        firstName: "Davgasuren",
        lastName: "Batbold",
        role: "Founder",
        work: "Beelog Tech",
        picture: "Batmunkh_Enkhtaivan",
      },
      {
        topic: "Dynamic Ads",
        firstName: "Batmunkh",
        lastName: "Enkhtaivan",
        role: "Team Leader",
        work: "Tenox",
        picture: "Batmunkh_Enkhtaivan",
      },
      {
        topic: "Plugin architecture",
        firstName: "BatAmar",
        lastName: "Battulga",
        role: "CTO",
        work: "Erxes",
        picture: "BatAmar_Battulga",
      },
      {
        topic: "Architecting for video call based telemed app",
        firstName: "Munkh-Abdul",
        lastName: "Mikael",
        role: "CTO",
        work: "Clinica",
        picture: "Munkh-Abdul_Mikael",
      },
      {
        topic:
          "Architecting for a nationwide enterprise-grade mobile app. Use case: eMongolia",
        firstName: "Batbayar",
        lastName: "Bazarragchaa",
        role: "CTO",
        work: "AstVision",
        picture: "Batbayar_Bazarragchaa",
      },
      {
        topic:
          "Stream processing data in real-time using Apache Kafka and Apache Samza",
        firstName: "Matus",
        lastName: "Faro",
        role: "Architecture Lead",
        work: "AND Global",
        picture: "Matus_Faro",
      },
      {
        topic:
          "TomYo.io - is a drag-and-drop app builder for educational content creators",
        firstName: "Erkhembayar",
        lastName: "Gantulga",
        role: "CTO",
        work: "TomYo EdTech",
        picture: "Erkhembayar_Gantulga",
      },
      {
        topic: "Indie game developer and his first game",
        firstName: "Monhoo",
        lastName: "Batraa",
        role: "Indie Game Developer",
        work: "Alpha games",
        picture: "Erkhembayar_Gantulga",
      },
      {
        topic: "Integrating with Unity / Unreal engines",
        firstName: "Batzorig",
        lastName: "Byambabaatar",
        role: "VR Dev / PM",
        work: "Digital Solutions Mongolia",
        picture: "Erkhembayar_Gantulga",
      },
      {
        topic: "Reliving History in VR",
        firstName: "Namuun",
        lastName: "Bayarsaikhan",
        role: "VR Dev / PM",
        work: "Digital Solutions Mongolia",
        picture: "Erkhembayar_Gantulga",
      },
    ],
  },
]
export const events = {
  "Tech Talks_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  "Women Techmakers_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  Workshops_: [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  AMA_: [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  "Panel Discussions_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "18:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
}
