export const speaker = [
  {
    title: "Women in Tech_",
    persons: [
      {
        firstName: "Oyun-Erdene",
        lastName: "Namsrai",
        role: "Professor",
        work: "National University of Mongolia ",
        picture: "Oyun-erdene",
      },
      {
        firstName: "Bayarmaa",
        lastName: "Gantumur",
        role: "Business Analyst / Project Manager",
        work: "Datacare LLC",
        picture: "Yesui_Batsukh",
      },
      {
        firstName: "Urandelger",
        lastName: "Ochirkhuyag",
        role: "CTO",
        work: "SmartData",
        picture: "urandelger",
      },
      {
        firstName: "Naran",
        lastName: "Batjargal",
        role: "Co-founder/COO",
        work: "Erxes Inc",
        picture: "Yesui_Batsukh",
      },
      {
        firstName: "Yesui",
        lastName: "Batsukh",
        role: "Academic manager / Project manager",
        work: "Nest Academy / Nest Solutions",
        picture: "Yesui_Batsukh",
      },
    ],
  },
  {
    title: "Panel Discussions_",
    persons: [
      {
        firstName: "Bolortuya",
        lastName: "Bayantur",
        role: "Data Quality Analyst",
        work: "Rio Tinto",
        picture: "misheel",
      },
      {
        firstName: "Deglee",
        lastName: "Ganzorig",
        role: "Graphic designer",
        work: "Central TV",
        picture: "misheel",
      },
      {
        firstName: "Misheel",
        lastName: "Batbuyan",
        role: "Instructor",
        work: "Nest Academy",
        picture: "misheel",
      },
      {
        firstName: "Anu-Ujin",
        lastName: "Bat-Ulzii",
        role: "Sr Front-end developer",
        work: "erxes",
        picture: "misheel",
      },
      {
        firstName: "Eja",
        lastName: "Batbold",
        role: "",
        work: "Tomyo edtech",
        picture: "Eja Batbold",
      },
      {
        firstName: "Enkhtuya",
        lastName: "Dandar",
        role: "Мэдээллийн технологийн төвийн захирал/Тэргүүлэх аудитор",
        work: "Үндэсний Аудитын Газар",
        picture: "misheel",
      },
      {
        firstName: "Otgonbayar",
        lastName: "Molom",
        role: "CEO/Founder",
        work: "DigIT LLC",
        picture: "misheel",
      },
      {
        firstName: "Dulgoon",
        lastName: "",
        role: "Founder / Sr UX Designer",
        work: "User Experience Academy / Mezorn Technology",
        picture: "misheel",
      },
    ],
  },
  {
    title: "Workshops_",
    persons: [],
  },
  {
    title: "Tech Talks_",
    persons: [
      {
        firstName: "Zolboobayar",
        lastName: "Gantumur",
        role: "Tech Lead",
        work: "Meta Global Inc LLC",
        picture: "Zolboobayar_Gantumur",
      },
      {
        firstName: "Usukhbayar",
        lastName: "Ganbaatar",
        role: "Sr Mobile Developer",
        work: "Mezorn",
        picture: "Usukhbayar_Ganbaatar",
      },
      {
        firstName: "Gansoronzon",
        lastName: "Norovgachil",
        role: "Sr Mobile Engineer",
        work: "Meta / Facebook",
        picture: "Gansoronzon_Norovgachil",
      },
      {
        firstName: "Anu",
        lastName: "Otgonjargal",
        role: "Front-end Developer",
        work: "Steppelink LLC",
        picture: "Anu Otonjargal",
      },
      {
        firstName: "Ariunaa",
        lastName: "Ganbat",
        role: "UX / UI designer",
        work: "And Systems Tech",
        picture: "Zolboobayar_Gantumur",
      },
      {
        firstName: "Tuvshintur",
        lastName: "Tserendorj",
        role: "Founder",
        work: "KMP",
        picture: "Tuvshintur_Tserendorj",
      },
      {
        topic: "Recommendation System",
        firstName: "Tungalag",
        lastName: "Ziinaa",
        role: "Data Scientist",
        work: "Freelancer",
        picture: "Tungalag_Ziinaa",
      },
      {
        firstName: "Khongorzul",
        lastName: "Munkhbat",
        role: "ML Engineer",
        work: "MMusic",
        picture: "Khongorzul_Munkhbat",
      },
      {
        firstName: "Tumur-Ochir",
        lastName: "Nasanjargal",
        role: "Senior ML Engineer",
        work: "And Systems Tech LLC",
        picture: "Tumur-Ochir_Nasanjargal",
      },
      {
        firstName: "Munkh-Od",
        lastName: "Ganzorigt",
        role: "CTO",
        work: "DiverseSolutions",
        picture: "Munkh-Od_Ganzorigt",
      },
      {
        firstName: "Tuvshintsenguun",
        lastName: "Erdenejargal",
        role: "Software Test Engineer",
        work: "Input Output Global",
        picture: "Tuvshintsenguun_Erdenejargal",
      },
      {
        firstName: "Ganbayar",
        lastName: "Uuganbayar",
        role: "Cyber security researcher",
        work: "University of Oxford",
        picture: "Munkh-Od_Ganzorigt",
      },
      {
        firstName: "Tengis",
        lastName: "Sukhee",
        role: "Information security advisor",
        work: "Indepenent",
        picture: "Tengis_Sukhee",
      },
      {
        firstName: "Bilguun",
        lastName: "Bayarmagnai",
        role: "CTO",
        work: "Nomadays LLC",
        picture: "Bilguun_Bayarmagnai",
      },
      {
        firstName: "Bilguun",
        lastName: "Bayarsaikhan",
        role: "Senior Software Engineer",
        work: "Unimedia Solutions",
        picture: "Bilguun_Bayarsaikhan",
      },
      {
        firstName: "Dulmandakh",
        lastName: "Sukhbaatar",
        role: "Founder / CEO",
        work: "Khuur Music Group LLC",
        picture: "Dulmandakh_Sukhbaatar",
      },
      {
        firstName: "Lkhavuujal",
        lastName: "Nipra",
        role: "Director of DevOps Division",
        work: "Grapecity Mongolia LLC",
        picture: "Lkhavuujal_Nipra",
      },
      {
        firstName: "Davgasuren",
        lastName: "Batbold",
        role: "Founder",
        work: "Beelog Tech",
        picture: "Batmunkh_Enkhtaivan",
      },
      {
        firstName: "Batmunkh",
        lastName: "Enkhtaivan",
        role: "Team Leader",
        work: "Tenox",
        picture: "Batmunkh_Enkhtaivan",
      },
      {
        firstName: "BatAmar",
        lastName: "Battulga",
        role: "CTO",
        work: "Erxes",
        picture: "BatAmar_Battulga",
      },
      {
        firstName: "Munkh-Abdul",
        lastName: "Mikael",
        role: "CTO",
        work: "Clinica",
        picture: "Munkh-Abdul_Mikael",
      },
      {
        firstName: "Batbayar",
        lastName: "Bazarragchaa",
        role: "CTO",
        work: "AstVision",
        picture: "Batbayar_Bazarragchaa",
      },
      {
        firstName: "Matus",
        lastName: "Faro",
        role: "Architecture Lead",
        work: "AND Global",
        picture: "Matus_Faro",
      },
      {
        firstName: "Erkhembayar",
        lastName: "Gantulga",
        role: "CTO",
        work: "TomYo EdTech",
        picture: "Erkhembayar_Gantulga",
      },
      {
        firstName: "Monhoo",
        lastName: "Batraa",
        role: "Indie Game Developer",
        work: "Alpha games",
        picture: "Erkhembayar_Gantulga",
      },
      {
        firstName: "Batzorig",
        lastName: "Byambabaatar",
        role: "VR Dev / PM",
        work: "Digital Solutions Mongolia",
        picture: "Erkhembayar_Gantulga",
      },
      {
        firstName: "Namuun",
        lastName: "Bayarsaikhan",
        role: "VR Dev / PM",
        work: "Digital Solutions Mongolia",
        picture: "Erkhembayar_Gantulga",
      },
    ],
  },
]
export const events = {
  "Tech Talks_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  "Women Techmakers_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  Workshops_: [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  AMA_: [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "17:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "17:20",
      endTime: "17:40",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
  "Panel Discussions_": [
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "8:00",
      endTime: "9:30",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "11:00",
      endTime: "12:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "13:00",
      endTime: "14:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "14:30",
      endTime: "15:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "16:00",
      endTime: "18:00",
    },
    {
      name: "Tech1 event",
      description: "This is a tech event",
      startTime: "18:00",
      endTime: "20: 00",
    },
  ],
}
